language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="f76eeb4b-4f37-4e36-bcee-e9295dd4fdd6"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - job4jstudy@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always